### PR TITLE
Bump Django to version 4.

### PR DESCRIPTION
**Pull request by akatsoulas**

### CODE REVIEW

**Comment by akatsoulas** [comment]
@willkg r?

**Comment by willkg** [comment]
Why are we switching this to Python 3.10? I thought we wanted to keep using the minimal supported Python version.

**Comment by akatsoulas** [comment]
Good point, I switched to Python 3.9 and Django 4.0.4. @willkg another pass?

**Comment by akatsoulas** [comment]
Please ignore my last comment. I totally messed up the EOL dates.

**Comment by willkg** [comment]
I created issue #43 which covers the needs that resulted in this PR. I did PR #44 which addresses those needs per our plan in #43.

**Pull request closed without merging**
