### PR TITLE
Drop support for Python 3.7 and update docker images (#67)

### LINKED ISSUE #67: drop support for Python 3.7
Python 3.7 is no longer supported. We should drop support for it.

https://endoflife.date/python

### PR DESCRIPTION
**Pull request by willkg**
Fixes #67

### CODE REVIEW

**Comment by willkg** [comment]
@akatsoulas I think I did this right. Does it look right to you? Also, do we want to update the docker images to different debian version? Right now they're using bullseye, but we could update them to bookworm.

**Review by akatsoulas — APPROVED** [review]
lgtm :+1:

**Comment by akatsoulas** [comment]
Good point about the Debian images. Would you like this tackled in this PR or in a separate one?

**Comment by willkg** [comment]
I'll do them in a follow-up PR. Thank you!

**Pull request merged**
