### PR TITLE
Fixes and maintenance

### LINKED ISSUE #50: Firefox can not be started
In #47 Selium support was added by @akatsoulas but the pipeline from https://github.com/mozilla/mozilla-django-oidc/pull/459 still doesn't work.
I have a quick look at it and I think there is a problem with the Firefox version installed in the Docker container.

1. I started the container and loaded the python venv:
```
docker run --rm -it  mozilla/oidc-testprovider:oidc_e2e_setup_py37-latest bash
root@58fa7788940c:/# . testrp_env/bin/activate
```

2. I tryd a simple splinter call
```python
(testrp_env) root@58fa7788940c:/# python
Python 3.7.13 (default, May 28 2022, 14:49:57)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from splinter import Browser
>>>
>>> with Browser("firefox", headless=True) as browser:
...     browser.visit("https://jinja101.infrastructureascode.ch")
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/testrp_env/lib/python3.7/site-packages/splinter/browser.py", line 99, in Browser
    return get_driver(driver, retry_count=retry_count, *args, **kwargs)
  File "/testrp_env/lib/python3.7/site-packages/splinter/browser.py", line 74, in get_driver
    raise err
  File "/testrp_env/lib/python3.7/site-packages/splinter/browser.py", line 70, in get_driver
    return driver(*args, **kwargs)
  File "/testrp_env/lib/python3.7/site-packages/splinter/driver/webdriver/firefox.py", line 74, in __init__
    **kwargs
  File "/testrp_env/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/testrp_env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/testrp_env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/testrp_env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/testrp_env/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process

>>> exit()
```

3. I wanted to check the installed firefox version and got the following error:
```
(testrp_env) root@58fa7788940c:/# /opt/firefox/firefox --verison
XPCOMGlueLoad error for file /opt/firefox/libxul.so:
libasound.so.2: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
(testrp_env) root@58fa7788940c:/# /opt/firefox/firefox --headless
XPCOMGlueLoad error for file /opt/firefox/libxul.so:
libasound.so.2: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```

4. I just installed a random firefox version and could start it
```
wget https://download-installer.cdn.mozilla.net/pub/firefox/releases/91.0.2/linux-x86_64/en-US/firefox-91.0.2.tar.bz2 -O /tmp/firefox.tar.bz2
tar xvf /tmp/firefox.tar.bz2 -C /opt

(testrp_env) root@58fa7788940c:/# /opt/firefox/firefox --version
Mozilla Firefox 91.0.2

(testrp_env) root@58fa7788940c:/# /opt/firefox/firefox --headless
*** You are running in headless mode.
[GFX1-]: glxtest: libpci missing
[GFX1-]: glxtest: libGL.so.1 missing
[GFX1-]: glxtest: libEGL missing
[GFX1-]: No GPUs detected via PCI
[GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
```

5. I tested the splinter code again and it worked.
```python
(testrp_env) root@58fa7788940c:/# python
Python 3.7.13 (default, May 28 2022, 14:49:57)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from splinter import Browser
>>> with Browser("firefox", headless=True) as browser:
...     browser.visit("https://jinja101.infrastructureascode.ch")
...
>>> exit()
```

I just picked a completely random Firefox version, but I didn't get any traceback with this one, so it looks better to me. 

Hopefully this helps somehow.

### PR DESCRIPTION
**Pull request by akatsoulas**
This PR has a couple of fixes and a bit of maintenance for the OIDC lib.

* It fixes #50 by using `bullseye` instead of `stretch`
* It restores the delete functionality. This allows the tearDown method of the integration tests to delete all users from the database. Without it the tests are failing. The setUp method tries to create a new user but the username and email are already taken. 
* I wasn't able to use the `account/delete` from the django-user-accounts lib and force a deletion so I added a new view which deletes all users.
* New version of splinter requires the definition of selenium3 in requirements

### CODE REVIEW

**Review by willkg — APPROVED** [review]
Looks good to me!

**Comment by willkg** [comment]
@akatsoulas Want me to tag and do a release after you merge this?

**Comment by akatsoulas** [comment]
@willkg that would be great! Thank you!!

**Comment by willkg** [comment]
I did a 0.10.5 release and the images are on docker hub now.

**Pull request merged**
