### PR TITLE
Add selenium in requirements.

### PR DESCRIPTION
**Pull request by akatsoulas**

### CODE REVIEW

**Comment by akatsoulas** [comment]
@willkg r?

Tests are failing in the oidc lib b/c it cannot find `selenium`
https://app.circleci.com/pipelines/github/mozilla/mozilla-django-oidc/168/workflows/8f7d06ff-c98e-47a9-93b5-9f5085daa829/jobs/4175

**Comment by willkg** [comment]
Did the previous set of images have selenium installed?

**Comment by willkg** [comment]
I checked the older images and they don't have selenium installed either.

If we're going to install selenium, we should switch the images to install a specific known-working combination of geckodriver, firefox, and selenium. We'd probably also want a test to make sure that it works, too.

How'd the e2e tests work before? Did Django pull in Selenium before Django 4 or something like that?

**Comment by willkg** [comment]
Looks like splinter changed its selenium support:

https://github.com/cobrateam/splinter/commit/16970c15bb0897853858e56638947990ac4c78e0#diff-0767be0cc3355e3418a5927bf321d85f3bdf4e8d527025cfc07d7ee69dcc6497R23-R33

Because it's not pinned here:

https://github.com/mozilla/docker-test-mozilla-django-oidc/blob/main/testrp/requirements.txt#L6

Then we pick up whatever versions of things. Ugh.

@akatsoulas Do you know for sure whether this fixes it? Or do we need to go in and pin everything to specific known-working versions of things?

**Comment by willkg** [comment]
One more comment: it'd probably be better to add the selenium requirement as a splinter extra so then we pick up a version that splinter works with:

https://splinter.readthedocs.io/en/latest/drivers/firefox.html#dependencies

**Comment by akatsoulas** [comment]
I tested locally the installation of the packages and I was able to reproduce the error. Defining `selenium` fixes it.

**Comment by akatsoulas** [comment]
@willkg pr updated

**Comment by willkg** [comment]
I'll cut a new version now.

**Pull request merged**
